---
deployment:
  tasks:
    - /bin/cp -rf /home/u2838272/repositories/anahtarteslimsera/site/* /home/u2838272/anahtarteslimsera.com/
    - /bin/cp -f /home/u2838272/repositories/anahtarteslimsera/site/.htaccess /home/u2838272/anahtarteslimsera.com/.htaccess
    - /bin/mkdir -p /home/u2838272/anahtarteslimsera.com/storage/leads
    - /bin/chmod 755 /home/u2838272/anahtarteslimsera.com/storage
    - /bin/chmod 755 /home/u2838272/anahtarteslimsera.com/storage/leads
