name: cPanel Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update from Remote
        run: |
          curl -k -v -u "${{ secrets.CPANEL_USER }}:${{ secrets.CPANEL_PASS }}" \
            "https://cpls34.srvpanel.com:2083/execute/VersionControl/update" \
            --data-urlencode "repository=/home/u2838272/repositories/anahtarteslimsera" \
            2>&1 | grep -v "Authorization:"
          echo "--- exit: $?"

      - name: Deploy HEAD Commit
        if: success()
        run: |
          curl -k -s -u "${{ secrets.CPANEL_USER }}:${{ secrets.CPANEL_PASS }}" \
            "https://cpls34.srvpanel.com:2083/execute/VersionControlDeployment/create" \
            --data-urlencode "repository=/home/u2838272/repositories/anahtarteslimsera"
          echo ""
